# Generated by Django 5.0.4 on 2024-05-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadAnalyzeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mySound_file', models.FileField(upload_to='vocalReportSource/')),
                ('compareSound_file', models.FileField(upload_to='vocalReportSource/')),
            ],
        ),
    ]
