# Generated by Django 5.0.4 on 2024-05-21 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadanalyzefile',
            name='fCompareSound_name',
            field=models.CharField(default='default', max_length=255),
        ),
        migrations.AddField(
            model_name='uploadanalyzefile',
            name='fMySound_name',
            field=models.CharField(default='default', max_length=255),
        ),
    ]
