# Generated by Django 5.0.4 on 2024-05-26 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modal', '0004_selectedplaylist'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedplaylist',
            name='song_url',
            field=models.CharField(default='none', max_length=255),
        ),
    ]
