# Generated by Django 5.0.4 on 2024-05-24 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermaxminfile',
            name='max_file_name',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AddField(
            model_name='usermaxminfile',
            name='min_file_name',
            field=models.CharField(default='none', max_length=255),
        ),
    ]
