# Generated by Django 5.0.4 on 2024-05-25 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_usermaxminfile_max_file_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.CharField(default='none', max_length=255)),
                ('img2', models.CharField(default='none', max_length=255)),
                ('img3', models.CharField(default='none', max_length=255)),
                ('artist1', models.CharField(default='none', max_length=255)),
                ('artist2', models.CharField(default='none', max_length=255)),
                ('artist3', models.CharField(default='none', max_length=255)),
                ('title1', models.CharField(default='none', max_length=255)),
                ('title2', models.CharField(default='none', max_length=255)),
                ('title3', models.CharField(default='none', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
