# Generated by Django 5.0.4 on 2024-05-26 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_playlistinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlistinfo',
            name='songurl1',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AddField(
            model_name='playlistinfo',
            name='songurl2',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AddField(
            model_name='playlistinfo',
            name='songurl3',
            field=models.CharField(default='none', max_length=255),
        ),
    ]
