# Generated by Django 5.0.4 on 2024-05-21 05:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('user_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('ID', models.CharField(max_length=50, unique=True)),
                ('user_mood', models.DecimalField(decimal_places=2, max_digits=4)),
                ('user_energy', models.DecimalField(decimal_places=2, max_digits=4)),
                ('user_tempo', models.DecimalField(decimal_places=2, max_digits=4)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superadmin', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='MaxminNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_note', models.CharField(max_length=5)),
                ('min_note', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='UploadMAXMIN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_file', models.FileField(upload_to='userVoice/')),
                ('min_file', models.FileField(upload_to='userVoice/')),
            ],
        ),
    ]
