# Generated by Django 5.0.4 on 2024-05-05 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Upload_MAXMIN',
            new_name='UploadMAXMIN',
        ),
    ]
